name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: ${{ matrix.python-version }}
    - name: Set up virtualenv
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install virtualenv
        python3 -m virtualenv venv
        source venv/bin/activate
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: prokope.settings
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        DEBUG: "False"
      run: |
        python3 manage.py test
